### ISSUE TITLE
Markers don't get updated until touching the map view

### ISSUE THREAD

**Issue by JarvanMo** [valentingrigorean/arcgis_maps_flutter#11]
In the demo project, markers are randomly generated. When you click the refresh button,markers don't get updated until touching the screen.
I only test this on Android side.

**Comment by JarvanMo** [comment]
It should be duplicated with #9

**Comment by JarvanMo** [comment]
The is casued by Flutter 3.0. See https://github.com/flutter/flutter/issues/103686

**Comment by valentingrigorean** [comment]
@JarvanMo I did the same fix the google maps made on https://github.com/flutter/plugins/pull/5787 hopefully this works
