### ISSUE TITLE
Basemap is not loaded.

### ISSUE THREAD

**Issue by JarvanMo** [valentingrigorean/arcgis_maps_flutter#15]
Basemap is not loaded successfully when I merge code from master. I also run the sample, it has the same issue.

**Comment by JarvanMo** [comment]
Only on Android side.

**Comment by valentingrigorean** [comment]
@JarvanMo can you tell me what screen does not work? Map 2D? if that is the case i comment the ApiKey. After setting back the API key the basemap for [Map 2d](https://github.com/valentingrigorean/arcgis_maps_flutter/blob/master/example/lib/map_page.dart#L44) is working again the same for #16 

![image](https://user-images.githubusercontent.com/5297143/180598593-218c5b2c-4a89-406c-9d9a-2d68be0af67b.png)

**Comment by JarvanMo** [comment]
Could you please tell me what changes impact on this? The problem is that my own project not works after I merged your recent updates. I remember that in the previous versions, I also commented code about enviroment setup, including license and apiKey, the Map2D still works.  It works well on iOS even the apiKey line is commented.

**Comment by JarvanMo** [comment]
![Screenshot_1658569507](https://user-images.githubusercontent.com/11608487/180600151-80a5fb90-4887-4829-987e-b3f629a7085f.png)
I don't think it's a issue related apiKey. From my point of view, the demo project should not be related apiKey. If ArcGis map is not setup with keys, it should works as well but show Developer License only watermark.

**Comment by JarvanMo** [comment]
![Uploading Simulator Screen Shot - iPhone 13 Pro - 2022-07-23 at 17.46.08.png…]()

**Comment by JarvanMo** [comment]
![Simulator Screen Shot - iPhone 13 Pro - 2022-07-23 at 17 46 08](https://user-images.githubusercontent.com/11608487/180600310-14bc5822-c2f8-4870-b57f-050533c004d9.png)

You can the screenshot from iOS, it works well without apiKey.

**Comment by valentingrigorean** [comment]
@JarvanMo the issue is from the native library
![image](https://user-images.githubusercontent.com/5297143/180601658-aa31b12c-15e2-49d9-9637-94456e3ffa76.png)

and this is the log I get
```
E/MainActivity: Map load failed: Check getCause() for further error information.
E/MainActivity: Map load failed: Token Required.
```
![Screenshot_1658572878](https://user-images.githubusercontent.com/5297143/180601755-50221a16-f719-4fc0-84fb-2e8ca1d0188e.png)

With apiKey is working
```java
ArcGISRuntimeEnvironment.setApiKey("apiKey");
```

```
D/MainActivity: Map: LOADED
```
![Screenshot_1658572979](https://user-images.githubusercontent.com/5297143/180601806-c1976391-2e91-4b04-965d-b19e8523ff7a.png)

So I'm clueless why iOS is working and android is not but that is the reason.

**Comment by JarvanMo** [comment]
For my experience with native ArcGis SDK, the sdk should works without apiKey, just like the current iOS platform. And I have run the demo project without apiKey before, it worked too. I don't want to say the current Android codebase is wrong, but I think some changes impact on this. My own project always works until I merged your changes yesterday. I need to figureout why.

**Comment by JarvanMo** [comment]
I checked with my previous native Android project, and commented authentication, the map is still loaded with Developers only.

**Comment by valentingrigorean** [comment]
@JarvanMo they might change something with a newer version. But the prev comment is based on a demo project with
```
 implementation 'com.esri.arcgisruntime:arcgis-android:100.14.1'
``` 
And this is what I get when putting a wrong apiKey. Putting the correct apiKey the maps load as expected.
```
E/MainActivity: Map load failed: Check getCause() for further error information.
E/MainActivity: Map load failed: The API key `*piKey` is invalid, expired, or does not have access to the resource: `https://basemaps-api.arcgis.com/arcgis/rest/services/styles/OSM:Standard`. Please visit https://developers.arcgis.com/api-keys to configure the API key to access the resource, or to create a new API key.
```

Also, u can see https://github.com/valentingrigorean/arcgis_maps_flutter/commit/b16b293fcb0fd8fa43c371ce09b73562110fb33c API become deprecated. But on iOS is still okay to use the old impl

https://developers.arcgis.com/android/api-reference/reference/com/esri/arcgisruntime/mapping/Basemap.html#createOpenStreetMap() this change seems to be from 100.14 forward.

Anyway, there is nothing I can do to make a load correctly so for now you have to provide a demo ApiKey or production apiKey for some maps. As u can see not all maps are affected.

**Comment by valentingrigorean** [comment]
@JarvanMo one suggestion is to downgrade the API version for the android project.

**Comment by JarvanMo** [comment]
I just tried with my native project with 100.13.2 and it worked too. Of course, it's not using openStreetMap, it's a custom basemap.

**Comment by JarvanMo** [comment]
This plugin used 100.13 long before if my memory wasn't lost. Both 13 and 14 works.

**Comment by valentingrigorean** [comment]
@JarvanMo did you try it to see if basemap loads with a native project?

**Comment by valentingrigorean** [comment]
@JarvanMo i found the issue https://github.com/valentingrigorean/arcgis_maps_flutter/commit/5b69c5ae7081cfb3e2299f893ab8ad4f8777d829
I fixed and is on master already.

**Comment by JarvanMo** [comment]
@valentingrigorean It works now. Thank you very much for helping me. You saved my life^_^
