### ISSUE TITLE
example(iOS) crashed with Flutter 3.3.5

### ISSUE THREAD

**Issue by JarvanMo** [valentingrigorean/arcgis_maps_flutter#24]
I try to run the example but crashed with Flutter 3.3.5. Here is the output:
```
Exception: Unable to launch com.valentingrigorean.example on 8F97679A-D4E8-4AA6-8B0D-C128493D22CF:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "com.valentingrigorean.example" failed.
The process did launch, but has since exited or crashed.
  Command: xcrun simctl launch 8F97679A-D4E8-4AA6-8B0D-C128493D22CF com.valentingrigorean.example --enable-dart-profiling --enable-checked-mode --verify-entry-points --start-paused --observatory-port=0
Error launching application on iPhone 13 Pro Max.
```
Do you have any ideas about this? Thanks.

**Comment by JarvanMo** [comment]
dyld: Library not loaded: @rpath/ArcGIS.framework/ArcGIS
  Referenced from: /private/var/containers/Bundle/Application/7281500F-FD92-4F26-8CA7-B6B7900D6A00/Runner.app/Runner
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by JarvanMo** [comment]
Xcode 14.0.1

**Comment by valentingrigorean** [comment]
@JarvanMo i can't reproduce it.Can you go manually to example/ios and run
```
pod install
```
Also can be sure you do a clean install(uninstall app on emulator).
Also if u don't have .env file i saw i get an error. i added a [sample](https://github.com/valentingrigorean/arcgis_maps_flutter/blob/master/example/.env-sample)
```
    note: Building targets in dependency order
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
 Result bundle written to path:
    	/var/folders/_2/lzmn5xc15dj6q7j3dv7kmwkh0000gn/T/flutter_tools.0OkwWq/flutter_ios_build_temp_dirUJ47sN/temporary_xcresult_bundle
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

```

**Comment by JarvanMo** [comment]
Thank you. I'll have a try.

**Comment by JarvanMo** [comment]
Still facing the issue. I'll try to upgrade my macOS.

**Comment by valentingrigorean** [comment]
@JarvanMo is on a device or a simulator? i tried only simulator maybe there is an issue with example on real device

**Comment by JarvanMo** [comment]
Both are the same issue. I try to run from xcode and the get the error.
dyld: Library not loaded: @rpath/ArcGIS.framework/ArcGIS
Referenced from:

**Comment by valentingrigorean** [comment]
@JarvanMo I tried it on diff laptop and it works without any issues.
