### ISSUE TITLE
Add Support for Offline Vector Tile Package Base Maps

### ISSUE THREAD

**Issue by jakeshapley-wdfw** [valentingrigorean/arcgis_maps_flutter#31]
The plugin currently supports mobile map packages. We need support for vector tile packages like [this](https://wdfw-fp-sport-regs-mobile-prod.s3.us-west-2.amazonaws.com/basemaps/vectors/fish_basemap.vtpk) one. Note, this particular vector tile package only has coverage for the U.S. state of Washington.

**Comment by valentingrigorean** [comment]
added in #30
