### ISSUE TITLE
Is it possible to support extent for geometry?

### ISSUE THREAD

**Issue by JarvanMo** [valentingrigorean/arcgis_maps_flutter#53]

**Comment by valentingrigorean** [comment]
@JarvanMo We can create a method in  [GeometryEngine](https://github.com/valentingrigorean/arcgis_maps_flutter/blob/master/lib/src/geometry/geometry_engine.dart)  and create maybe extension on Geometry to access it but will be async.

**Comment by JarvanMo** [comment]
Thank you. I can do that.
