### ISSUE TITLE
W/ArcgisMapController( 4815): loadOfflineMap: Failed to load map.Invalid access.

### ISSUE THREAD

**Issue by hrithikm2cd** [valentingrigorean/arcgis_maps_flutter#61]
I am trying to load an MMPK file with the example. The file exists inside the download folder of my device's internal storage. And the file exists when checked from the package path_provider. I used the example code from your package and it throws the following error
**W/ArcgisMapController( 4815): loadOfflineMap: Failed to load map.Invalid access.**
Any solution for this?

**Comment by valentingrigorean** [comment]
@ hrithikm2cd, This looks like the app doesn't have permission.
 Try adding an extension and see if that works. If not try to copy to the app directory and try again

**Comment by hrithikm2cd** [comment]
@valentingrigorean 
I tried asking for storage permission, but it still gives the same error. Tried it with permission_handler package. The popup appears and with that I am able to allow the app permission to access storage.
SDK : 31 
OS : Android
Code for the file

`     import 'dart:io';
      import 'package:arcgis_maps_flutter/arcgis_maps_flutter.dart';
      import 'package:flutter/material.dart';
      import 'package:flutter/services.dart';
      import 'package:path_provider/path_provider.dart';
      import 'package:permission_handler/permission_handler.dart';
      
      class MobilePageMobileMapPackage extends StatefulWidget {
        const MobilePageMobileMapPackage({Key? key}) : super(key: key);
      
        @override
        State<MobilePageMobileMapPackage> createState() =>
            _MobilePageMobileMapPackageState();
      }
      
      class _MobilePageMobileMapPackageState
          extends State<MobilePageMobileMapPackage> {
        ArcGISMap? _offlineMap;
      
        @override
        void initState() {
          super.initState();
          _loadOfflineMap();
        }
      
        @override
        void dispose() {
          super.dispose();
        }
      
        @override
        Widget build(BuildContext context) {
          return Scaffold(
            appBar: AppBar(
              title: const Text('Mobile map package'),
            ),
            body: _offlineMap == null
                ? const Center(
                    child: CircularProgressIndicator.adaptive(),
                  )
                : ArcgisMapView(
                    map: _offlineMap!,
                    onMapLoaded: (error) {
                      if (error != null) {
                        debugPrint('Error: $error');
                      }
                    },
                  ),
          );
        }
      
        Future<String?> getDownloadPath() async {
          Directory? directory;
          try {
            if (Platform.isIOS) {
              directory = await getApplicationDocumentsDirectory();
            } else {
              directory = Directory('/storage/emulated/0/Download');
              // Put file in global download folder, if for an unknown reason it didn't exist, we fallback
              // ignore: avoid_slow_async_io
              if (!await directory.exists()) {
                directory = await getExternalStorageDirectory();
              } else {
                print("Directory hai $directory");
              }
            }
          } catch (err) {
            print("Cannot get download folder path");
          }
          return directory?.path;
        }
      
        Future<void> _loadOfflineMap() async {
          var status = await Permission.storage.status;
          if (!status.isGranted) {
            await Permission.storage.request();
          } else {
            final directory = await getDownloadPath();
      
            final file = File(directory! + "/map.mmpk");
            final fileExists = await file.exists();
      
            if (!fileExists) {
              print('file does not exist');
              final result = await _moveMapToLocalStorage(file);
              if (!result) return;
            } else {
              print("FILE EXISTS " + file.path);
              //moveFileToAppFolder(file);
            }
      
            _offlineMap = ArcGISMap.offlineMap(file.path);
            setState(() {});
          }
        }
      
        Future<bool> _moveMapToLocalStorage(File file) async {
          try {
            var dir = await getApplicationDocumentsDirectory();
            if (await dir.exists()) {
              final data = await rootBundle.load(file.path);
              await file.create(recursive: true);
              await file.writeAsBytes(
                  data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
              return true;
            }
            return false;
          } catch (e) {
            debugPrint('Error moving file: $e');
            return false;
          }
        }
      
        Future<void> moveFileToAppFolder(File file) async {
          // Get the path to the app's documents directory
          Directory appDocumentsDirectory = await getApplicationDocumentsDirectory();
      
          // Specify the destination folder within the app's documents directory
          Directory appFolder = Directory('${appDocumentsDirectory.path}/app_folder');
          if (!await appFolder.exists()) {
            await appFolder.create(recursive: true);
          }
      
          // Build the destination path
          String fileName = file.path.split('/').last; // Get the file name
          String destinationPath = '${appFolder.path}/$fileName';
      
          // Move the file to the destination path
        }
      }
`

**Comment by valentingrigorean** [comment]
@hrithikm2cd I try to run your sample, and I'm getting 
```dart
 if (!fileExists) {
        print('file does not exist');
        final result = await _moveMapToLocalStorage(file);
        if (!result) return;
      } else {
        print("FILE EXISTS " + file.path);
        final bytes = await file.readAsBytes();
        //moveFileToAppFolder(file);
      }
```
On this line       final bytes = await file.readAsBytes(); with this message:
```
E/flutter (21036): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/Yellowstone.mmpk' (OS Error: Permission denied, errno = 13)
E/flutter (21036): #0      _checkForErrorResponse (dart:io/common.dart:55:9)
E/flutter (21036): #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
E/flutter (21036): <asynchronous suspension>
E/flutter (21036): #2      _MobilePageMobileMapPackageState._loadOfflineMap (package:arcgis_maps_flutter_example/map_page_mobile_map_package.dart:92:21)
E/flutter (21036): <asynchronous suspension>
E/flutter (21036): 
```
The issue is not from the ArcGIS library itself. It's about permission.

Even if you have requested permissions in your AndroidManifest.xml, it doesn't necessarily mean they have been granted. You should also check and request permissions at runtime, especially if you target Android 6 (API 23) or higher, as you have done in your code. But please note the MANAGE_EXTERNAL_STORAGE permission requires additional steps to be granted; it's not as straightforward as the other permissions. Also, remember, from Android 11 (API 30) onwards, you can no longer use the READ_EXTERNAL_STORAGE to access any file in the shared storage. Use Storage Access Framework or MediaStore API for this.

Could you research how to fix the permission first, then try again?
If the issue persists after fixing the permission, you can reopen it, and I will look at it.

**Comment by hrithikm2cd** [comment]
Understood, Thank you for the response. @valentingrigorean 
And many thanks for creating this library.

**Comment by xyhuangjia** [comment]
can't load offline map with .tpk file
