### ISSUE TITLE
can't load offline map with .tpk file

### ISSUE THREAD

**Issue by xyhuangjia** [valentingrigorean/arcgis_maps_flutter#62]
can't load offline map with .tpk file

my code like this

![WeChat7713e9097b266d4f9e3621e7a7b174c6](https://github.com/valentingrigorean/arcgis_maps_flutter/assets/12025585/ee58c574-3680-47cd-a44d-f5e926c4b3e0)

error log
```
flutter: Error: ArcgisError{code: 7, errorMessage: Not found., additionalMessage: Mobile map package is missing a .info file., innerErrorMessage: null, errorDomain: ErrorDomain.unknown}
```

**Comment by valentingrigorean** [comment]
@xyhuangjia I don't think the error is with the Flutter library. You can try as well to load in the native app (android or iOS) 
https://developers.arcgis.com/android/api-reference/reference/com/esri/arcgisruntime/mapping/MobileMapPackage.html
### ChatGPT response

This error message implies that your ArcGIS application could not find the required `.info` file in your Mobile Map Package (MMPK).

A Mobile Map Package consolidates maps into a single file (.mmpk) that can be shared across ArcGIS products and used even when offline. The `.info` file is part of the MMPK and is necessary for the ArcGIS system to interpret the data.

Here are a few things you might check or try to fix this error:

1. **Verify that the Mobile Map Package file is intact and complete.** If you've downloaded it from a source or moved it, it's possible the file might have been corrupted or some parts of it may not have been transferred. If this is the case, you might want to try to download or move the file again.

2. **Ensure that the MMPK file is accessible.** Make sure that the path to the MMPK file is correct, and that the user running the ArcGIS software has the necessary permissions to access the file.

3. **Recreate the Mobile Map Package.** If you've created the MMPK yourself and it's missing the `.info` file, there might have been an issue during the creation process. You might need to recreate the package and make sure it completes without errors.

4. **Update your ArcGIS software.** If you're running an older version of the software, it might not be able to handle certain MMPK files correctly. Make sure you're using a version of the software that is compatible with the MMPK file you're trying to use.

If none of these suggestions solve the problem, it would be advisable to contact ESRI support or check in GIS-related forums like Geonet for a more specific solution.
