### ISSUE TITLE
Basemaps not loading, Token required

### ISSUE THREAD

**Issue by atnegrete** [valentingrigorean/arcgis_maps_flutter#64]
Basically same issue as a previously resolved one #15 

- Android
- Flutter 3.13.1 • channel stable

```
W/ArcgisMapController(11826): changeMap: Failed to load map.Check getCause() for further error information.
W/ArcgisMapController(11826): changeMap: Failed to load map.Token Required.
D/MAP     (11826): loadStatusChanged: FAILED_TO_LOAD
E/MAP     (11826): loadStatusChanged: Check getCause() for further error information.
E/MAP     (11826): loadStatusChanged: Token Required.
```

**Comment by valentingrigorean** [comment]
@atnegrete Hey, that apiKey issue. 
Can you try the migration-2.0.0 branch?
Here I set the credentials/tokens
https://github.com/valentingrigorean/arcgis_maps_flutter/blob/migration-2.0.0/example/lib/utils/credentials.dart
